name: CI/CD

on:
  # Permite ejecutar el flujo de trabajo de manera manual
  workflow_dispatch:
  
  # Ejecuta el flujo de trabajo al hacer un git push  
  # Comentamos el trigger, de esa manera No se ejecuta los trabajos
  # push:
  #    branches: ["main"]
  #  branches:
  #    - main  # Se ejecutará cuando haya un push en main
  pull_request:
     branches: ["main"]
    #  branches:
  #    - main    # Se ejecutará cuando haya un pull request en main   

jobs:
# Trabajo/job 1 (build-and-push): Integración contínua (CI). Construye a imagen de la aplicación y la sube a un registro de contenedores (Docker Hub)
  build-and-push:
# El runner será un Ubuntu    
    runs-on: ubuntu-latest

    steps:
# Copia el repositorio en el runner      
      - name: Checkout del código
        uses: actions/checkout@v4

# Usa una GitHub Actions para iniciar sesión en el registro de Docker Hub.        
      - name: Login en Docker Hub
        uses: docker/login-action@v3
        with:
# Hay que configurar los siguientes secretos
# Settings > Secrets and variables > Actions > New repository secret
# DOCKER_USERNAME → Tu usuario de Docker Hub.
# DOCKER_PASSWORD → Tu token de acceso de Docker Hub (en lugar de la contraseña, genera un token en Docker Hub). Asiga TODOS los permisos al TOKEN.

          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
# Construye la imagen
      - name: Construir y etiquetar la imagen (BUILD)
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/lamp-crud-app:latest .
# Sube la imagen a un registro      
      - name: Subir imagen a Docker Hub (PUSH)
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/lamp-crud-app:latest

# Otra manera es usar una GitHub Actions que contruye y sube la imagen al registro de Docker Hub
      #- name: Build and push
      #  uses: docker/build-push-action@v4
      #  with:
      #    context: .
      #    push: true
      #    tags: ${{ secrets.DOCKER_USERNAME }}/lamp-crud-app:latest

 
# Trabajo/job 2 (deploy): Despliegue contínuo (CD). Actualiza aplicación  en producción y descarga la imagen del registro de contenedores (Docker Hub)      
  deploy:
    runs-on: ubuntu-latest
  # Hasta que no se acabe el trabajo 1, no se inicia este trabajo
    needs: build-and-push
  # Usa una GitHub actions que va a hacer un SSH al servidor de producción  
  # Hay que configurar los siguientes secretos:
  # SSH_HOST → IP elástica o ombre DNS servidor de producción
  # SSH_USER → Usuario SSH. En EC2 de tipo Ubuntu en AWS: ubuntu      
  # SSH_KEY → Clave privada acceso por certificado
  # SSH_PORT → Puerto de escucha servicio SSH. Normalmente el 22.   
    steps:
      - name: Despliegue en servidor de produccion
        uses: appleboy/ssh-action@v1.2.1
        with:
           host: ${{ secrets.SSH_HOST }}
           username: ${{ secrets.SSH_USER }}
           key: ${{ secrets.SSH_KEY }}
           port: ${{ secrets.SSH_PORT }}   
           script: |
               cd environment/aplicacion-crud-php-produccion/
               git pull origin main
               docker compose down
               docker compose pull apache
               docker compose up -d             
